### ISSUE TITLE
Test Results for 7 Sound Cards (Additional Sound Card Drivers do not seem to work)

### ISSUE THREAD

**Issue by hjnijlunsing** [sbemu-x/sbemu-x#11]
Hi I just tested 7 sound cards with SBEMU-X here are the results:
(Tested only with Quake)

- Sound Blaster Live 5.1 [SB0100] for reference:
Works, no issues. Sound a bit on the low side; but same as SB-EMU

- CMI8738-PCI-6CH-LX, CMI-8738-PCI-6CH, CMI8738-PCI-SX
Sound Card: CMI
Real mode support: enabled
Protected mode support: enabled
OPL3 Emulation at port 388: enabled
Crash 
Sometime followed after a few seconds by:
JemmEx: Exception 0D or 06

- Sound Blaster 16 PCI
Sound Card: ENS
Real mode support: enabled
Protected mode support: enabled
OPL3 Emulation at port 388: enabled
Crash 

- ESS-Solo-1 [ES1938S]
No Supported Sound Card Found

- AC97 [ULi Electronics Inc. M5455]
No Supported Sound Card Found

**Comment by ghost** [comment]
@crazii Just use your normal account, no problem. Thanks for the tests.

**Comment by crazii** [comment]
> @crazii Just use your normal account, no problem. Thanks for the tests.

what?

**Comment by thp** [comment]
Closing, let's continue the discussion over at https://github.com/crazii/SBEMU/issues/55
