### ISSUE TITLE
Incompatibility between upstream HX/HDPMI and crazii's fork

### ISSUE THREAD

**Issue by volkertb** [sbemu-x/sbemu-x#12]
(First of all, to anybody reading this: feel free to chime in here if I'm not describing or summarizing any of this correctly. Thanks.)

If I understand correctly, during the earlier stages of development of SBEMU, @crazii [created a fork](https://github.com/crazii/HX) of HDPMI32i (part of @Baron-von-Riedesel's [HX project](https://github.com/Baron-von-Riedesel/HX)), since it did not yet have the necessary functionality that SBEMU depended on at the time, particularly being able to run in ring 0 and having the ability to port trap I/O operations.

However, this functionality was later added to HDPMI32i in the upstream HX project, but the upstream version and the fork have this implemented in mutually incompatible ways. In the meantime, @Baron-von-Riedesel started on the [VSBHDA](https://github.com/Baron-von-Riedesel/VSBHDA) project that has a similar goal as SBEMU.

See also these posts:

- https://github.com/Baron-von-Riedesel/HX/issues/11#issuecomment-1773962231
- https://www.vogons.org/viewtopic.php?p=1178183#p1178183

For the sbemu-x fork, would it be prudent to make it compatible with the upstream version of HDPMI32i? I don't mean this out of disrespect for @crazii's work. He has been doing amazing work on SBEMU. But at this point, he is having to maintain this HX fork just for SBEMU, whereas the upstream project also exists for broader use, not just for SBEMU and VSBHDA. Also, the original author is obviously much more familiar and experienced in maintining that project.

By the way, the HDPMI32i sources in the HX project (both the upstream version and @crazii's fork) aren't trivial to build, at least in my experience. At the moment, the project needs some work before it can successfully cross-compile from Linux. In its current state, it can apparently only be built from DOS or Windows, and even in DOS, I haven't yet been able to build it. (I haven't tried Windows.) But that's actually a separate issue that we might also want to look into.

**Comment by crazii** [comment]
I myself don't like an incompatible fork.
It is possible but not easy, especially for compatibility test again for all machines. besides there're some extra code added to the fork, needed by sbemu, we can continue talking to baron to see if he had done the same feature.

I remember asked for the feature first and he says NO "for now". (don't remember where and when), that's why I created another fork, and talked about a PR. but he might ignore or miss it, with out reply(https://github.com/Baron-von-Riedesel/HX/issues/27#issuecomment-1345266377).  and later he just implemented the feature. it was just a pity.

**Comment by crazii** [comment]
It comes to me that, what if we have a built-in DPMI server? Is it possible, or even necessary?  it could be, make SBEMU more compact and independent.
I've seen that the driver of SB PCI has its own DPMI (on some only sources).
Also for VIAFMTSR which implements FM emulation on VIA, works for both real mode & pm games. how it handles the port IO?
if the hardware generate a special interrupt and the VIIAFMTSR handles it, then it might not need trap the ports.

**Comment by volkertb** [comment]
> I remember asked for the feature first and he says NO "for now". (don't remember where and when), that's why I created another fork, and talked about a PR. but he might ignore or miss it, with out reply([Baron-von-Riedesel/HX#27 (comment)](https://github.com/Baron-von-Riedesel/HX/issues/27#issuecomment-1345266377)). and later he just implemented the feature. it was just a pity.

To be fair, people can change their minds over time. :slightly_smiling_face: 3 years ago, I opened a [feature request to have support for QPI (QEMM's port-trapping API) added to Jemm](https://github.com/Baron-von-Riedesel/Jemm/issues/6). At the time, he felt that it would be [too much work and not worth the effort](https://github.com/volkertb/temu-vsb/issues/4#issuecomment-703244131), so I closed the feature request. Fortunately, he eventually did implement QPI in the form of a Jemm Loadable Module, which SBEMU now depends on for port-trapping in real mode games, right?

We might want to take a look at how his [VSBHDA](https://github.com/Baron-von-Riedesel/VSBHDA) project makes use of the port-trapping functionality that he added to HDPMI.

If I understand correctly, the first step is figuring out if the functionality that was added to HDPMI32i after your fork includes all the required functionality. Is that correct?

**Comment by volkertb** [comment]
> It comes to me that, what if we have a built-in DPMI server? Is it possible, or even necessary? it could be, make SBEMU more compact and independent. I've seen that the driver of SB PCI has its own DPMI (on some only sources). Also for VIAFMTSR which implements FM emulation on VIA, works for both real mode & pm games. how it handles the port IO? if the hardware generate a special interrupt and the VIIAFMTSR handles it, then it might not need trap the ports.

I know there are some hardware-assisted methods like DSDMA, but those required support in both the sound card and the motherboard chipset, which too my knowledge isn't available in more recent chipsets.

As for your question whether integrating a lightweight DPMI server in a project like SBEMU or sbemu-x would be the way to go, I lack the expertise to answer that. However, wouldn't we be reinventing the wheel by going that route?

At the end of the day, doesn't VSBHDA need the same port-trapping functionality for it to work as SBEMU does? If so, it should all be there, right? Let me try looking up the commits in the upstream HX/HDPMI project, so we can study them and find out.

**Comment by volkertb** [comment]
At the time of this writing, your fork is [14 commits behind](https://github.com/crazii/HX/compare/master...Baron-von-Riedesel:HX:master) the upstream HX/HDPMI project.

And indeed, at least some of those commits seem to be adding or updating a port-trapping API in HDPMI.

Notably this one: https://github.com/crazii/HX/commit/2f18ab8cdf9e30ce1d8812798b7e47af8f9684f1

In later commits, this functionality appears to be improved, and documentation about it is added.

Can you tell just by glancing through those commits how different they are from the port-trapping functionality that you added to your fork?

**Comment by volkertb** [comment]
@crazii Also, do you by any chance have working build instructions for HDPMI, either your fork or Baron-von-Riedesel's upstream version? I couldn't get it to build, neither in Linux and in DOS.

It's the last puzzle piece for the the GitHub Actions Workflow in [this draft PR](https://github.com/crazii/SBEMU/pull/21), which would automatically build a ready-to-use USB image with FreeDOS and SBEMU.

Thanks! :slightly_smiling_face:

**Comment by crazii** [comment]
> At the time of this writing, your fork is [14 commits behind](https://github.com/crazii/HX/compare/master...Baron-von-Riedesel:HX:master) the upstream HX/HDPMI project.
> 
> And indeed, at least some of those commits seem to be adding or updating a port-trapping API in HDPMI.
> 
> Notably this one: [crazii/HX@2f18ab8](https://github.com/crazii/HX/commit/2f18ab8cdf9e30ce1d8812798b7e47af8f9684f1)
> 
> In later commits, this functionality appears to be improved, and documentation about it is added.
> 
> Can you tell just by glancing through those commits how different they are from the port-trapping functionality that you added to your fork?

I checked commit but sorry that I'm not skilled enough to tell the differences by a glance. it seems implementing the port-trapping api in multiple source locations. the truth is I'm not quite familiar with the HDPMI source, I just dug into the port-trapping entry code and simply add implementations, ignoring the whole picture & architecture thing.

**Comment by crazii** [comment]
> @crazii Also, do you by any chance have working build instructions for HDPMI, either your fork or Baron-von-Riedesel's upstream version? I couldn't get it to build, neither in Linux and in DOS.
> 
> It's the last puzzle piece for the the GitHub Actions Workflow in [this draft PR](https://github.com/crazii/SBEMU/pull/21), which would automatically build a ready-to-use USB image with FreeDOS and SBEMU.
> 
> Thanks! 🙂

I built it under win10 only. what step are you stuck into exactly?
The JWasm have dos edition. But JWLink doesn't... what you also need is a nmake utility that runs under dos.
Meanwhile I'll try to find a working nmake under dos, or stub the win32 jwlink & nmake so that it works under HX env.

**Comment by crazii** [comment]
Since there's a makefile now for cross compilation, there's another way that you can compile it under WSL/cygwin/mingw or somthing, and built hdpmi under windows.
Last time I checked there's a djgpp package under WSL ubuntu.

**Comment by crazii** [comment]
I just found a nmake from MSC++7.0 that works under DOS, with stubbing of JWlink & JWLib win32, and tiny modification of the original makefile, I manged to build it under DOS.
I'll commit the makefile change and then upload a build env zip for DOS, with a readme.

**Comment by 4nd3r50ncr** [comment]
That's cool bro, we'll be able to compile in DOS, we just need to separate the makefile from the original for Linux. The interesting thing in this case is to be able to compile both of us, so as not to have system dependencies.

**Comment by crazii** [comment]
I've committed the changes. check this out: https://github.com/crazii/HX/commits/master

**Comment by crazii** [comment]
> That's cool bro, we'll be able to compile in DOS, we just need to separate the makefile from the original for Linux. The interesting thing in this case is to be able to compile both of us, so as not to have system dependencies.

I was too lazy  to write a makefile for SBEMU, I think he's using the makefile that generated by RHIDE.
"maybe next time" :D.

**Comment by 4nd3r50ncr** [comment]
If I'm not mistaken, I posted a makefile here to compile for DOS using djgpp.

**Comment by crazii** [comment]
Oh yes, I guess that makefile can be used for both djgpp, under dos and linux.

**Comment by crazii** [comment]
I remember merged the PR of thp that uses cross toolchain & makefile a few days ago.  Are you thp himslef?
Can you create a PR of latest changes that with the new drivers?

**Comment by volkertb** [comment]
@crazii No, @thp has his own GitHub account. Mentioning him here, so that he sees your question.

**Comment by volkertb** [comment]
@crazii Thanks for adding the ZIP file with the build tools to your HX fork. However, there are two issues with it:

- Just to be safe, I ran BUILDDOS.zip through VirusTotal, and [14 virus scanners detected malware in it](https://www.virustotal.com/gui/file/26c8e813b231acffdf510780ef5b4cf6de2e8fece397b2c9f3db74f5aa9cab42/detection). I'll try to narrow down exactly which file(s) in the ZIP file is/are getting flagged.
- Microsoft NMAKE is not open source and to my knowledge it's not freeware either, so it can't legally be included in the project like that.

An open source alternative for NMAKE is [Open Watcom](https://github.com/open-watcom/open-watcom-v2)'s WMAKE utility, which supports a Microsoft NMAKE compatibility mode with the `-ms` parameter. In various documents in the HX project, it is indicated that either NMAKE or WMAKE with the `-ms` option can be used to build the sources. In the project files [Src/DIRS](https://github.com/crazii/HX/blob/master/Src/DIRS) and [SrcEmu/DIRS](https://github.com/crazii/HX/blob/master/SrcEmu/DIRS) you can see a line `MAKE=nmake.exe /nologo` with under that a commented-out line `MAKE=wmake.exe -h -ms`. Have you already tried commenting out the upper line and uncommenting the lower line in these files and building the code with WMAKE? I tried that, but I remember running into some other issue.

I really hope we can build this with WMAKE, since then we'd finally have a completely open source toolchain to build both HDPMI32i and SBEMU (and by extension sbemu-x).

Thanks again!

**Comment by volkertb** [comment]
Considering the detected malware IDs, it could have been a false positive, bit it's strange that as many as 14 virus scanners flagged it. Usually, when there is a false positive in VirusTotal, it only gets flagged by just one or two engines.

**Comment by crazii** [comment]
I tried with nmake from openwatcom(OW), but it didn't work and crashes. I didn't know about the virus, that computer is running under win10 with ms defender on, I will check later.
I've noticed the nmake copyright thing, and I thought about using the nmake from visual c++6, since vc++6 was released to the public by MS, but I'm not sure it is redistributable. The best solution is to use nmake from OW. I was using wmake on windows, but I forgot the details, it's a long time. May need check on that again, tell me if it works.

**Comment by crazii** [comment]
I think it's a false alarm. It might be possible that after PESTUB, it looks like a virus pattern code. I'm free of malwares for many years and I'm quite confident about it, if not 100% sure.
You can create a similar zip according the readme in builddos.zip to see if there is any problem. It's safe to extract it as long as you don't execute anything in it.

**Comment by volkertb** [comment]
That sounds familiar. I believe I remember getting a crash too when I tried to build it with WMAKE.

I'll try to reproduce this with the stuff in BUILDDOS.zip. Maybe it's a regression in the [Open Watcom v2 fork](https://github.com/open-watcom/open-watcom-v2), and it might work fine with the older WMAKE version that comes with [Open Watcom v1.9](https://github.com/open-watcom/open-watcom-1.9). The Open Watcom v2 fork is actively maintained by @jmalak, so I'll open a GitHub issue there if we can confirm that the project builds fine with NMAKE, but not with WMAKE, all else being equal.

In the meantime, to simplify the [GitHub Actions Workflow for the SBEMU project](https://github.com/crazii/SBEMU/pull/21), could you maybe publish an up-to-date release of the HDPMI32i binary on the [releases page of your HX fork](https://github.com/crazii/HX/releases)? That way, at least the I can have the workflow download and package such a newer version of the binary in the USB images that can built on each SBEMU release. Thanks!

**Comment by crazii** [comment]
I test the dos version of wmake and it works. I was previously using win32 version of nmake+wmake from openwatcom and PESTUB them both, but they run with empty commands but crash HDPMI on make.
the license file from openwatcom is also included.
cheers, the risk is gone: https://github.com/crazii/HX/commits/master

**Comment by volkertb** [comment]
Good to know that it at least builds correctly with the DOS version of WMAKE.

Thanks for investigating this, and for replacing NMAKE with WMAKE in the project.

I know license concerns are a pain in the butt, but keeping things legal makes the software truly free to use, improve and distribute by everyone.

Maybe I'll create a separate merge request for your HX fork to have the binary built and released automatically any merge commit or merge to `master`, and then I'll extend my existing merge request for your SBEMU project to download the latest release from your HX fork. Let's see how far I get with that this weekend.

**Comment by crazii** [comment]
latest release of the fork: https://github.com/crazii/HX/releases/tag/v0.1-beta3

**Comment by volkertb** [comment]
You're fast this evening (or whatever the time of day is in your time zone)! Thanks. :relaxed:

**Comment by crazii** [comment]
It's early in the dawn and github now is more assessable than other time of the day. (still got connection timeout/reset sometimes).

**Comment by volkertb** [comment]
I'll be heading to bed soon, but I hope to update my pull request for your SBEMU project tomorrow, so it can finally be merged. I'll also update it to take the recently merged PRs by @thp into account. (No more case sensitivity workarounds necessary anymore.)

**Comment by 4nd3r50ncr** [comment]
@crazii We need to take this more seriously, you know, the project is very good. But you need a license urgently. And maybe it will give more reason for other people to participate. Avoid using something “personal” as an extension to the project or using proprietary license programs. An example of this is Jemm, nothing about QEMM, or anything else, and so on. I would be more excited to help, really.

**Comment by crazii** [comment]
Yes, fair enough. QEMM is just optional and is only mentioned but not provided, is that OK or we don't talk about it at all?
Are you planning to rewrite the sound drivers and replace mpxplay code? I appreciate that if you do.

**Comment by 4nd3r50ncr** [comment]
It's a big challenge, but it's possible to do it in free time, at least for both of us. But it's like I told you, you first need to define a license, with the exception of mpxplay. Preferably gnu gpl. Create a license file, you can easily find this on the GNU website on how to do it. Regarding mpxplay, if the author has at least the compassion to make his code useful, he should see this. try to convince him again. Because for me as a music player it’s not useful, at least for me it’s not useful. I had already thought that it was possible to emulate the sound a long time ago, time wouldn't let me, but I realized that it was possible, so you launched your sbemu code, but for your sbemu, you must define a license, as I said previously .

**Comment by volkertb** [comment]
> Yes, fair enough. QEMM is just optional and is only mentioned but not provided, is that OK or we don't talk about it at all? Are you planning to rewrite the sound drivers and replace mpxplay code? I appreciate that if you do.

I don't see any problems with it being optional! Choice is good. In my opinion, it's fine to support QEMM as an alternative for those who want or need to use QEMM for some reason, as long as we focus primarily on a solution that is both open source and still maintained, which indeed makes Jemm the most obvious solution to focus on. That way, people who want to use SBEMU or xbemu-x are not forced to use any non-free or closed source components, and also it will hopefully allow SBEMU or sbemu-x to eventually be distributed as part of FreeDOS.

**Comment by volkertb** [comment]
> It's a big challenge, but it's possible to do it in free time, at least for both of us. But it's like I told you, you first need to define a license, with the exception of mpxplay. Preferably gnu gpl. Create a license file, you can easily find this on the GNU website on how to do it. Regarding mpxplay, if the author has at least the compassion to make his code useful, he should see this. try to convince him again. Because for me as a music player it’s not useful, at least for me it’s not useful. I had already thought that it was possible to emulate the sound a long time ago, time wouldn't let me, but I realized that it was possible, so you launched your sbemu code, but for your sbemu, you must define a license, as I said previously .

Some of the source files in the Mpxplay code, particularly some of the sound driver sources, include copyright and license headers that imply that the Mpxplay developer actually copied that code from GPL-licensed projects such as the ALSA project and the Linux kernel. If that can be confirmed, then we can confront the Mpxplay developer with that, and point out that the GPL-incompatible restrictions that he is imposing on the full Mpxplay sources are actually themselves license violations.

**Comment by crazii** [comment]
I think the author of mpxplay will agree on a GPL license at least for this piece of code. we don't need confront for now. I'll talk to him soon.

**Comment by crazii** [comment]
> It's a big challenge, but it's possible to do it in free time, at least for both of us. But it's like I told you, you first need to define a license, with the exception of mpxplay. Preferably gnu gpl. Create a license file, you can easily find this on the GNU website on how to do it. Regarding mpxplay, if the author has at least the compassion to make his code useful, he should see this. try to convince him again. Because for me as a music player it’s not useful, at least for me it’s not useful. I had already thought that it was possible to emulate the sound a long time ago, time wouldn't let me, but I realized that it was possible, so you launched your sbemu code, but for your sbemu, you must define a license, as I said previously .

It's hard for me to write drivers, I never did that before, but I can try, first I'll ask for a GPL license of mpxplay for the portion that's used for SBEMU/SBEMU-X.

**Comment by volkertb** [comment]
Let's not reinvent the wheel! Writing sound drivers from scratch is quite a challenge.

I've been trying to port/adapt drivers from the [OSS project](http://www.opensound.com/oss.html) and from the [FreeBSD sound driver sources](https://cgit.freebsd.org/src/tree/sys/dev/sound/pci/hda). We could also take a look at the [ALSA drivers](https://alsa-project.org/), which are used in the Linux kernel. All of these have proper licenses, either GPLv2 or licenses that are compatible with GPLv2 (MIT, BSD, etc.) Something like that's probably the way to go.

In another project I've been working on, I've been trying to port such drivers from other operating systems to the AIL/32 driver model, which was open-sourced by John Miles years ago, and can be used in protected mode applications, including hopefully SBEMU.

@crazii On a different topic: my MR for CI/CD for the SBEMU project is ready for final review: https://github.com/crazii/SBEMU/pull/21

**Comment by crazii** [comment]
> Let's not reinvent the wheel! Writing sound drivers from scratch is quite a challenge.
Agreed. Even porting ALSA drivers to DOS is a big challenge for me, but is much easier I guess.

I'll check the PR soon. Have a good night.

**Comment by Torinde** [comment]
Related: crazii/SBEMU/issues/40

**Comment by thp** [comment]
Let's continue the discussion over at https://github.com/crazii/SBEMU/issues/40
