### ISSUE TITLE
Loud constant noise when initializing the driver on sc_es1371

### ISSUE THREAD

**Issue by MFDGaming** [sbemu-x/sbemu-x#13]
When initializing the driver a loud constant noise gets played and when running a program that uses audio the computer locks up with a memory error

**Comment by Torinde** [comment]
I assume that's related to:
- https://github.com/crazii/SBEMU/issues/41

**Comment by MFDGaming** [comment]
> I assume that's related to:
> 
> * [SoundBlaster AudioPCI128 (CT4810) (CT2518/ES1371/ES1373) locks up when initializing crazii/SBEMU#41](https://github.com/crazii/SBEMU/issues/41)

Yes it is

**Comment by thp** [comment]
Closing here, let's continue the discussion over at https://github.com/crazii/SBEMU/issues/41
