### ISSUE TITLE
error compile makefile for DOS

### ISSUE THREAD

**Issue by ghost** [sbemu-x/sbemu-x#2]
[makefile.zip](https://github.com/sbemu-x/sbemu-x/files/12995683/makefile.zip)
Do you want to try to find out? @thp

**Comment by thp** [comment]
What is the error? That you can't build it in DOS? I haven't tested this, and not sure what the benefit of building onder DOS would be. Why don't you just build under Linux, macOS or Windows using DJGPP cross-compilation? It will be faster and you'll get access to a newer GCC. There's even prebuilt binaries for GCC 12.2 available here: https://github.com/andrewwutw/build-djgpp/releases

**Comment by ghost** [comment]
It was my last attempt at compiling directly under DOS, but the libraries were too outdated for DOS, so I gave up.
