### ISSUE TITLE
Merge or cooperate with the SoftMPU project

### ISSUE THREAD

**Issue by volkertb** [sbemu-x/sbemu-x#5]
Having one "unified" emulation solution that handles Sound Blaster DAC emulation, OPLx FM synthesis emulation and MPU-401 MIDI emulation would be the holy grail.

As far as I understand, the SoftMPU project in its current form has the same limitations that other port trapping emulators and DOS drivers other than SBEMU and VSBHDA do: they don't work with protected mode games.

SBEMU was intended from the start to work with both real mode and protected mode games.

Having the SoftMPU developers join forces with this project would be mutually beneficial, I think.

Alternatively, maybe the projects could continue to coexist independently while being able to share some mutual code.

Curious about what you all think of this.

**Comment by thp** [comment]
SoftMPU only implements MPU-401 intelligent mode on top of MPU-401 "UART" mode (or a serial port).

What you probably mean is to trap MIDI port I/O (SB-MIDI or MPU-401) and use a software synthesizer to make MPU-401 MIDI audible on the modern sound card?

**Comment by volkertb** [comment]
That too. But as we also talked about in issue #6, I believe dosemu-x should eventually be made flexible enough so that it would be capable of both:

- Emulating FM and MIDI synthesizers fully in software
- Redirecting FM and MIDI output to physical devices such as an OPL3PLT or an USB MIDI adapter (which indeed would include intelligent mode emulation)

A possible architecture for dosemu-x that I have in mind would be a completely modular one, with "pluggable" emulation cores, some of which offer full software emulation of things like FM synthesis, Roland MT-32 or General MIDI, and others that simply redirect such music streams to different hardware devices on the host, such as OPL3LPT, USB MIDI adapters, etc. It would also provide a way to add support for more physical PCM output devices overall, in addition to just the common ones (Intel HDA, AC'97, Sound Blaster Live!, etc).

So it would more or less evolve in more of a modular emulation "framework", which could be extended with modules, some of which would be included in the standard distribution, but with the possibility of other open-source projects popping up to work on different modules to extend it. For instance, a module that would implement Gravis Ultrasound emulation. The SoftMPU project could then perhaps evolve into such a module for sbemu-x, or forked into another project that would turn it into such a module.

Would it help to draw up an architectural design like that? It might be good to have a debate on the architecture and design of the project, if we want to extend it as we work on it further, and other developers join the project.

**Comment by volkertb** [comment]
I guess what I'm trying to say is that sbemu-x should focus on the following core functionality, which has been the toughest to solve:

- I/O Port trapping
- 8237-style (ISA) DMA emulation
- Compatibility with both real mode and protected mode games

Everything else (support for specific hardware, both on the emulation side and on the output back-end side) could then be built on top of that in a modular fashion. And for all of that, we could leverage plenty of already existing and mature open-source software projects.

**Comment by Torinde** [comment]
Related: Baron-von-Riedesel/VSBHDA/issues/5

**Comment by thp** [comment]
Closing. Let's continue over at https://github.com/Baron-von-Riedesel/VSBHDA/issues/5 and file this again in SBEMU if relevant. Thanks!
